language: bash
sudo: required
services:
- docker
before_install:
- git config --global user.name "$GH_USER"
- git config --global user.email "$GH_USER_EMAIL"
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN@github.com" > .git/credentials
- git config --global push.default simple
script:
- chmod ugo+x bin/*.sh
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker run -it -v $(pwd):/root/sources
  -e BINTRAY_USER -e BINTRAY_PASSWORD -e COVERALLS_TOKEN -e TRAVIS_BRANCH -e TRAVIS_TAG
  -e TRAVIS_PULL_REQUEST -e TRAVIS_BUILD_NUMBER -e TRAVIS_REPO_SLUG -w /root/sources
  maven:${MAVEN_DOCKER_VERSION}-jdk-8 bin/build.sh || true'
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && docker run -it -v $(pwd):/root/sources
  -w /root/sources maven:${MAVEN_DOCKER_VERSION}-jdk-8 mvn clean verify --settings
  settings.xml || true'
branches:
  except:
  - "/^release-candidate.*$/"
after_success:
- bin/release.sh
env:
  global:
  - MAVEN_DOCKER_VERSION=3.3.3
  - GH_USER="Sebastien Bortolussi"
  - GH_USER_EMAIL="sebastien.bortolussi@orange.com"
  - secure: lBRsZ5616NQe/P/PKR0QHdFqAG6Rj5w6p98bOeZPrMBzNlsL2kHEMm4xf4nDVxa9nYr5/PnSq+PePNAzh7+9z+Gp6q/7jUi+wxzXaz+aAEbp56ZPJbk05ZhV0MeUVn6iLNQt7ItYvqbEpArWg5ZW2+487b+oUEZXAMCMMzaaVAB5g6sUHE9K0ks2WIQRDWd/NjiVucx6sIE5BXfoQ3tYFEq2Vw2EpxHNkvZVNV1VvFELXD/l//71/EIpEJbGDLp1bVccBTzmKkpTRvkbNFGwT+vzp/Z1Dd7ZDDPOsNczazrCFTOmAU68IMWo08i18nYzBHRvTagVMs1mty0nCAjSq0HgcCfrtcNPRoQnYI1AX6jYevSEaCWptVSwxw0D5SJNElpOtuvWB8OGWpo0Ak1AvFNoQ2P7cGZ1P6bayMepkNKHd7VWavoaGkSYBp62XLbuLOyJixoUpIOrkKAv5qUHCfpsoYY9lpzg9QzGsBWPfOh07TTvpebT2dINwzy/kQTzNF5xMe8AlDQWGMsBH1MsmMyII3DMJ6wzW4lgGoaR8ERo/QJRlzGjrYQL90gmaG7/ZGyu2S7ip1z0Qa2zbwYoiiOuEToOpC+lQebL/Hh+ejkb/osC+zfj5I0bsH8tYI8Qs5QKBHIYeEA0pm4DGnjMNSioujl5PCZGNvJaNYMecPc=
  - secure: XTnr7B6SEL3n+Pbd+5xVFEnpzF7+HF0gESomPMHJrFHWc7/kRItwbF77M37eTkoKeHnL/xuNvc7aNQlRtOQ0omR57Na+/YLDjnh4KQTjkEdvS/GXSCpdw8h/jqBBmXq6pfuNHHgL+BYuaBmzYbfNS3J7sAKaqimlsdYJvobR/5uVNUQZZ7DppX4UNdcFR0Ntlg4CzBEHL0eQv30krBbN7zYxjrkYU0ZQQxN0eQ7VL8hLbapmLlok4JWek91s5w9l/tOlmKCdF/ThMHTR5IkiMPSkRBGyHFHFmurPSM1hxcnmGH2WJoKLtYUkW6ORlN8fdW42S9pNlseKGH0GOowC6ORi6zCFbhZmbEITXi2lxS22Dl3GanGcF9JO1Q3peZwOfQlGr4zLQUC5gN47hqwyrxqIa6oR5RAqFA7KrdgsuVtzVgq+mSZxVGDR6lrQPhCYKt4hQOeC5gu3661XiDGanNFkBVwi/KKigUCQwVfiyctZQjnoyreVpWl+m7wODMMZ5XFlc87jFEgqv5mxESAtrntSdJlitPNFSWigpqyJYdvgNBErh9SJ7dlv/V/Kal55nqyo2m0AwenbWKAWdF5PXJJJIXYdZOK/QozraIr2fNtlLh4AmUuXiAhWskRSZLY8ECNSdLo3krnFZds+SrTGYO6splkhWnno89ZcNzQTuUg=
  - secure: eovox+G0LDYqksE+vKpTi7Gh14OkPwBfbX4jw5FZ9jmEGOwmNUMYrv19lqJbaPa0WH7NwnnIBaD64vD9zwQMwgIs7amcpyDrc79oL4k55kwoJkrE1XdLgBB0vnnJzHXlMdBnJBkKtk35rhksmQKrAqiaMHSpgHq4X0DnWieBA5G00Rbbh0WKR8XQop/aANXNRQwH0PGX0l0G4qA73ExdJxxflmwvn/H31VC9wKug+kwqlJsGL4xVg23YRRc6h682WsDxH5t6jYW8LX9Jmteuqj678/sbfzsruHoVchxljoMd4da3mvEe5SvJ8Ea/DmCJWbbnjf57+lGjGXH3o8M8O+CF4OgHgXrpJF/Yjx5rrz0r23kPrEyRZRSP1eFj/ce05qYVoFG+K0agmNF9hRs7LYGMfA2LDh+kAMEOW/Z9N7h36WG/3KqgvNAoSX4AnYMR1xZHl135cU237tIFLjPxj0QqPvVB5RQfK3kQlbwqIBqTo1+XRw6dyo1ofbnY5f+x1kQWtokWV0jSLWCB3swqktcppINLBAfJpDIRzDF1+iM/A+OAl/r7DOrWl8OH+3FRKxd6s3D4f14tHzv3dignYCMULDRweriISyQR5mMtHIarr4xpZ6GVcfIXoRFfaJTjoCFUepbAWPQAXpyXByHIrAZ74uHy+XWAiCb04aUNJOc=
