language: bash
sudo: required
services:
- docker
before_install:
- git config --global user.name "$GH_USER"
- git config --global user.email "$GH_USER_EMAIL"
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials
- git config --global push.default simple
script:
- chmod ugo+x bin/*.sh
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker run -it -v $(pwd):/root/sources
  -e BINTRAY_USER -e BINTRAY_PASSWORD -e COVERALLS_TOKEN -e TRAVIS_BRANCH -e TRAVIS_TAG
  -e TRAVIS_PULL_REQUEST -e TRAVIS_BUILD_NUMBER -e TRAVIS_REPO_SLUG -w /root/sources
  maven:${MAVEN_DOCKER_VERSION}-jdk-8 bin/build.sh || true'
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && docker run -it -v $(pwd):/root/sources
  -w /root/sources maven:${MAVEN_DOCKER_VERSION}-jdk-8 mvn clean verify --settings
  settings.xml || true'
branches:
  except:
  - /^release-candidate.*$/
after_success:
- bin/release.sh
env:
  global:
  - MAVEN_DOCKER_VERSION=3.3.3
  - GH_USER="sbortolussi"
  - GH_USER_EMAIL="sebastien.bortolussi@orange.com"